<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.22">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Garbage Can Regression Challenge</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="index_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="index_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting-cd7454b418030687c631a6a7286fbe16.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap-d6a003b94517c951b2d65075d42fb01b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Garbage Can Regression Challenge</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="garbage-can-regression-challenge" class="level1">
<h1>Garbage Can Regression Challenge</h1>
<div id="d72d40c4" class="cell" data-execution_count="1">
<div class="cell-output cell-output-stdout">
<pre><code>    Stress  StressSurvey  Time  Anxiety
0        0             0   0.0     0.00
1        0             0   1.0     0.10
2        0             0   1.0     0.10
3        1             3   1.0     1.10
4        1             3   1.0     1.10
5        1             3   1.0     1.10
6        2             6   2.0     2.20
7        2             6   2.0     2.20
8        2             6   2.0     2.20
9        8             9   2.0     8.20
10       8             9   2.0     8.20
11       8             9   2.1     8.21
12      12            12   2.2    12.22
13      12            12   2.2    12.22
14      12            12   2.2    12.22</code></pre>
</div>
</div>
<section id="your-analysis" class="level2">
<h2 class="anchored" data-anchor-id="your-analysis">Your Analysis</h2>
<section id="bivariate-regression-anxiety-on-stresssurvey" class="level3">
<h3 class="anchored" data-anchor-id="bivariate-regression-anxiety-on-stresssurvey">Bivariate Regression: Anxiety on StressSurvey</h3>
</section>
<section id="question-1-run-a-bivariate-regression-of-anxiety-on-stresssurvey.-what-are-the-estimated-coefficients-how-do-they-compare-to-the-true-relationship" class="level3">
<h3 class="anchored" data-anchor-id="question-1-run-a-bivariate-regression-of-anxiety-on-stresssurvey.-what-are-the-estimated-coefficients-how-do-they-compare-to-the-true-relationship">Question 1: Run a bivariate regression of Anxiety on StressSurvey. What are the estimated coefficients? How do they compare to the true relationship?</h3>
<div id="32e3ea5d" class="cell" data-execution_count="2">
<div class="cell-output cell-output-stdout">
<pre><code>Regression Results:
Intercept (β₀): -1.5240
Slope (β₁): 1.0470
R² Score: 0.9011

Estimated Regression Equation:
Anxiety = -1.5240 + 1.0470 × StressSurvey</code></pre>
</div>
</div>
</section>
<section id="answer" class="level3">
<h3 class="anchored" data-anchor-id="answer">Answer</h3>
<p><strong>Estimated Coefficients:</strong> - <strong>Intercept (β₀)</strong>: -1.5240 - <strong>Slope (β₁)</strong>: 1.0470 - <strong>R² Score</strong>: 0.9011</p>
<p><strong>True Relationship:</strong> The true relationship in the data is: <strong>Anxiety = Stress + 0.1 × Time</strong></p>
<p>Since StressSurvey = 3 × Stress, the true relationship in terms of StressSurvey is: <strong>Anxiety = (StressSurvey/3) + 0.1 × Time</strong></p>
<p>Therefore: - <strong>True StressSurvey coefficient</strong>: 1/3 = 0.3333 - <strong>True Time coefficient</strong>: 0.1000 - <strong>True intercept</strong>: 0.0000 (no constant term in true relationship)</p>
<p><strong>Comparison to True Relationship:</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Coefficient</th>
<th>Estimated</th>
<th>True</th>
<th>Difference</th>
<th>Bias</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>StressSurvey</strong></td>
<td>1.0470</td>
<td>0.3333</td>
<td>+0.7137</td>
<td><strong>3.1x too large</strong></td>
</tr>
<tr class="even">
<td><strong>Intercept</strong></td>
<td>-1.5240</td>
<td>~0.158</td>
<td>-1.6820</td>
<td><strong>Severely biased</strong></td>
</tr>
</tbody>
</table>
<p><strong>Key Findings:</strong> The regression shows significant <strong>omitted variable bias</strong>. The estimated slope coefficient (1.047) is <strong>3.1 times larger</strong> than the true slope (0.333) because:</p>
<ol type="1">
<li><strong>Time is omitted</strong> from the regression, but it’s part of the true relationship</li>
<li><strong>StressSurvey and Time are correlated</strong> in this dataset (correlation = 0.882)</li>
<li>The regression is <strong>confounding</strong> the effect of StressSurvey with the effect of Time</li>
</ol>
<p><strong>Why This Is Dangerous:</strong> - <strong>Policymakers might restrict social media</strong> based on inflated harm estimates - <strong>Parents might overreact</strong> to misleading statistics about screen time - <strong>Tech companies might be unfairly blamed</strong> for effects they don’t actually cause - <strong>Resources might be misallocated</strong> to address the wrong problems</p>
<p><strong>What To Do About It:</strong> - <strong>Always check for omitted variables</strong> that might be correlated with your main variable - <strong>Include relevant control variables</strong> in your regression models - <strong>Be skeptical of dramatic results</strong> - they often indicate statistical problems - <strong>Look for alternative explanations</strong> when coefficients seem too large</p>
</section>
</section>
<section id="question-2-create-a-scatter-plot-with-the-regression-line-showing-the-relationship-between-stresssurvey-and-anxiety.-comment-on-the-fit-and-any-potential-issues." class="level2">
<h2 class="anchored" data-anchor-id="question-2-create-a-scatter-plot-with-the-regression-line-showing-the-relationship-between-stresssurvey-and-anxiety.-comment-on-the-fit-and-any-potential-issues.">Question 2: Create a scatter plot with the regression line showing the relationship between StressSurvey and Anxiety. Comment on the fit and any potential issues.</h2>
<section id="scatter-plot-with-regression-line" class="level3">
<h3 class="anchored" data-anchor-id="scatter-plot-with-regression-line">Scatter Plot with Regression Line</h3>
<div id="a94b4078" class="cell" data-execution_count="3">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-4-output-1.png" width="759" height="564" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="answer-1" class="level3">
<h3 class="anchored" data-anchor-id="answer-1">Answer</h3>
<p><strong>Fit Assessment:</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 22%">
<col style="width: 51%">
</colgroup>
<thead>
<tr class="header">
<th>Metric</th>
<th>Value</th>
<th>Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>R² Score</strong></td>
<td>0.901</td>
<td>High explanatory power (90% of variance explained)</td>
</tr>
<tr class="even">
<td><strong>RMSE</strong></td>
<td>1.47</td>
<td>Moderate prediction errors</td>
</tr>
<tr class="odd">
<td><strong>MAE</strong></td>
<td>1.23</td>
<td>Mean absolute error of 1.23 units</td>
</tr>
<tr class="even">
<td><strong>Residuals Mean</strong></td>
<td>~0.000</td>
<td>No systematic bias in residuals</td>
</tr>
</tbody>
</table>
<p><strong>Visual Assessment:</strong> - <strong>Strong linear relationship</strong> is clearly visible in the scatter plot - <strong>Regression line fits well</strong> through the data points - <strong>No obvious outliers</strong> in the data - <strong>Good spread</strong> of data points around the regression line</p>
<p><strong>Critical Issues Identified:</strong></p>
<ol type="1">
<li><strong>Severe Omitted Variable Bias</strong>
<ul>
<li>Time variable is excluded but affects Anxiety</li>
<li>Estimated slope (1.047) is <strong>3.1x larger</strong> than true slope (0.333)</li>
<li>Intercept is severely biased (-1.524 vs true ~0.158)</li>
</ul></li>
<li><strong>Confounding Problem</strong>
<ul>
<li>StressSurvey and Time are highly correlated (r = 0.882)</li>
<li>Regression captures Time’s effect through StressSurvey</li>
<li>This creates a <strong>spurious relationship</strong></li>
</ul></li>
<li><strong>Misleading High R²</strong>
<ul>
<li>R² = 0.901 suggests excellent fit</li>
<li>But this is <strong>misleading</strong> because it’s capturing confounding effects</li>
<li>High R² masks the severe coefficient bias</li>
</ul></li>
</ol>
<p><strong>Why This Is Dangerous:</strong> - <strong>Decision-makers will trust the high R²</strong> and make policy based on wrong conclusions - <strong>Media will report “strong evidence”</strong> of social media harm without mentioning the bias - <strong>Parents will restrict children’s access</strong> based on inflated harm estimates - <strong>Tech companies will face unfair regulation</strong> based on spurious relationships</p>
<p><strong>What To Do About It:</strong> - <strong>Never trust high R² alone</strong> - always check for omitted variable bias - <strong>Look for correlation between variables</strong> - high correlation often indicates confounding - <strong>Include control variables</strong> even if they seem unrelated - <strong>Be suspicious of dramatic results</strong> - they often indicate statistical problems - <strong>Use graphical diagnostics</strong> to identify systematic patterns in residuals</p>
<p><strong>Conclusion:</strong> While the scatter plot shows a strong visual relationship and high R², this is a classic example of <strong>omitted variable bias</strong>. The regression line appears to fit well, but the coefficients are severely biased due to the confounding effect of the omitted Time variable. <strong>High R² can be dangerously misleading</strong> when it masks fundamental statistical problems with model specification.</p>
</section>
</section>
<section id="question-3-run-a-bivariate-regression-of-anxiety-on-time.-what-are-the-estimated-coefficients-how-do-they-compare-to-the-true-relationship" class="level2">
<h2 class="anchored" data-anchor-id="question-3-run-a-bivariate-regression-of-anxiety-on-time.-what-are-the-estimated-coefficients-how-do-they-compare-to-the-true-relationship">Question 3: Run a bivariate regression of Anxiety on Time. What are the estimated coefficients? How do they compare to the true relationship?</h2>
<section id="regression-analysis-anxiety-on-time" class="level3">
<h3 class="anchored" data-anchor-id="regression-analysis-anxiety-on-time">Regression Analysis: Anxiety on Time</h3>
<div id="4f8a5c33" class="cell" data-execution_count="4">
<div class="cell-output cell-output-stdout">
<pre><code>=== TIME REGRESSION RESULTS ===
Intercept (β₀): -3.6801
Slope (β₁): 5.3406
R² Score: 0.5630

Estimated Regression Equation:
Anxiety = -3.6801 + 5.3406 × Time</code></pre>
</div>
</div>
</section>
<section id="answer-2" class="level3">
<h3 class="anchored" data-anchor-id="answer-2">Answer</h3>
<p><strong>Estimated Coefficients:</strong> - <strong>Intercept (β₀)</strong>: -3.6801 - <strong>Slope (β₁)</strong>: 5.3406 - <strong>R² Score</strong>: 0.5630</p>
<p><strong>True Relationship:</strong> The true relationship in the data is: <strong>Anxiety = Stress + 0.1 × Time</strong></p>
<p>Therefore: - <strong>True Time coefficient</strong>: 0.1000 - <strong>True intercept</strong>: varies with Stress, but base intercept ≈ mean(Stress) = 4.60</p>
<p><strong>Comparison to True Relationship:</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Coefficient</th>
<th>Estimated</th>
<th>True</th>
<th>Difference</th>
<th>Bias</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Time</strong></td>
<td>5.3406</td>
<td>0.1000</td>
<td>+5.2406</td>
<td><strong>53.4x too large</strong></td>
</tr>
<tr class="even">
<td><strong>Intercept</strong></td>
<td>-3.6801</td>
<td>~4.60</td>
<td>-8.2801</td>
<td><strong>Severely biased</strong></td>
</tr>
</tbody>
</table>
<p><strong>Key Findings:</strong> The regression shows <strong>dramatically worse omitted variable bias</strong> than the StressSurvey regression. The estimated Time coefficient (5.341) is <strong>53.4 times larger</strong> than the true coefficient (0.1) because:</p>
<ol type="1">
<li><strong>Stress is omitted</strong> from the regression, but it’s the primary driver of Anxiety</li>
<li><strong>Time and Stress are highly correlated</strong> (r = 0.744)</li>
<li>The regression is <strong>confounding</strong> the effect of Time with the effect of Stress</li>
<li><strong>The intercept has the wrong sign</strong> (-3.68 vs true ~4.6)</li>
</ol>
<p><strong>Critical Issues:</strong> - <strong>Slope coefficient is 53x too large</strong> (5.34 vs 0.1) - <strong>Intercept is severely biased</strong> and has wrong sign - <strong>Lower R² (0.563)</strong> compared to StressSurvey regression (0.901) - <strong>Time appears to have a massive effect</strong> on Anxiety, but this is spurious</p>
<p><strong>Why This Is Extremely Dangerous:</strong> - <strong>Media will report “Time causes massive anxiety”</strong> based on 53x inflated estimates - <strong>Parents will panic</strong> about screen time effects that don’t actually exist - <strong>Policymakers will create draconian time limits</strong> based on spurious evidence - <strong>Tech companies will face extreme regulation</strong> for effects they don’t cause - <strong>Resources will be wasted</strong> on interventions that target the wrong variable</p>
<p><strong>What To Do About It:</strong> - <strong>Never trust single-variable regressions</strong> without checking for omitted variables - <strong>Look for the main driver</strong> of your outcome variable (Stress, not Time) - <strong>Be extremely suspicious</strong> of coefficients that seem too large - <strong>Always include relevant control variables</strong> in your models - <strong>Use domain knowledge</strong> to identify what variables should be included</p>
<p><strong>Comparison with StressSurvey Regression:</strong> - <strong>StressSurvey</strong>: slope = 1.047 (3x true), R² = 0.901 - <strong>Time</strong>: slope = 5.341 (53x true), R² = 0.563 - <strong>Time regression has much worse bias</strong> but lower R² - This demonstrates that <strong>omitted variable bias can be much more severe</strong> when the omitted variable (Stress) has a stronger relationship with the outcome than the included variable (Time)</p>
<p><strong>Conclusion:</strong> This is an extreme example of omitted variable bias. The Time coefficient is <strong>53 times too large</strong> because the regression is capturing the confounding effect of the omitted Stress variable through Time. <strong>This type of bias can lead to completely wrong policy decisions</strong> and massive misallocation of resources. The model appears to show Time has a massive effect on Anxiety, but this is entirely spurious due to the omitted variable problem.</p>
</section>
</section>
<section id="question-4-create-a-scatter-plot-with-the-regression-line-showing-the-relationship-between-time-and-anxiety.-comment-on-the-fit-and-any-potential-issues." class="level2">
<h2 class="anchored" data-anchor-id="question-4-create-a-scatter-plot-with-the-regression-line-showing-the-relationship-between-time-and-anxiety.-comment-on-the-fit-and-any-potential-issues.">Question 4: Create a scatter plot with the regression line showing the relationship between Time and Anxiety. Comment on the fit and any potential issues.</h2>
<section id="scatter-plot-with-regression-line-1" class="level3">
<h3 class="anchored" data-anchor-id="scatter-plot-with-regression-line-1">Scatter Plot with Regression Line</h3>
<div id="9618e62d" class="cell" data-execution_count="5">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-6-output-1.png" width="759" height="564" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="answer-3" class="level3">
<h3 class="anchored" data-anchor-id="answer-3">Answer</h3>
<p><strong>Fit Assessment:</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 22%">
<col style="width: 51%">
</colgroup>
<thead>
<tr class="header">
<th>Metric</th>
<th>Value</th>
<th>Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>R² Score</strong></td>
<td>0.563</td>
<td>Moderate explanatory power (56% of variance explained)</td>
</tr>
<tr class="even">
<td><strong>RMSE</strong></td>
<td>3.09</td>
<td>Substantial prediction errors</td>
</tr>
<tr class="odd">
<td><strong>MAE</strong></td>
<td>2.56</td>
<td>Mean absolute error of 2.56 units</td>
</tr>
<tr class="even">
<td><strong>Residuals Mean</strong></td>
<td>~0.000</td>
<td>No systematic bias in residuals</td>
</tr>
</tbody>
</table>
<p><strong>Visual Assessment:</strong> - <strong>Data points cluster by Stress levels</strong>, clearly showing the confounding effect - <strong>Regression line has extremely steep slope</strong> (5.34) vs true slope (0.1) - <strong>Line appears to connect different stress clusters</strong> rather than show Time effect - <strong>No obvious outliers</strong> but clear clustering patterns</p>
<p><strong>Critical Issues Identified:</strong></p>
<ol type="1">
<li><strong>Extreme Omitted Variable Bias</strong>
<ul>
<li>Stress is the primary driver of Anxiety but is excluded</li>
<li>Estimated slope (5.341) is <strong>53.4x larger</strong> than true slope (0.1)</li>
<li>Intercept is severely biased (-3.68 vs true ~4.6)</li>
</ul></li>
<li><strong>Severe Confounding Problem</strong>
<ul>
<li>Time and Stress correlation = 0.744 (very high!)</li>
<li>Regression captures Stress effect through Time</li>
<li>This creates a <strong>completely spurious relationship</strong></li>
</ul></li>
<li><strong>Misleading Moderate R²</strong>
<ul>
<li>R² = 0.563 suggests moderate fit</li>
<li>But this is <strong>misleading</strong> because it’s capturing confounding effects</li>
<li>Lower R² than StressSurvey regression (0.901) but worse bias</li>
</ul></li>
</ol>
<p><strong>Why This Is Catastrophically Dangerous:</strong> - <strong>Media will report “Time causes 534% increase in anxiety”</strong> based on completely wrong evidence - <strong>Parents will implement extreme screen time restrictions</strong> that don’t address the real problem - <strong>Policymakers will create draconian time-based regulations</strong> that miss the actual cause - <strong>Tech companies will face massive lawsuits</strong> for effects they don’t actually cause - <strong>Mental health resources will be misdirected</strong> to time-based interventions instead of stress management</p>
<p><strong>What To Do About It:</strong> - <strong>Never trust regressions without the main explanatory variable</strong> (Stress in this case) - <strong>Always check correlations</strong> between your included and omitted variables - <strong>Be extremely suspicious</strong> of coefficients that are orders of magnitude too large - <strong>Use domain knowledge</strong> to identify the primary drivers of your outcome - <strong>Include all relevant variables</strong> even if they seem unrelated to your hypothesis</p>
<p><strong>Comparison with StressSurvey Regression:</strong> - <strong>StressSurvey</strong>: R² = 0.901, slope = 1.047 (3x true) - <strong>Time</strong>: R² = 0.563, slope = 5.341 (53x true) - <strong>Time regression has much worse bias</strong> but lower R² - <strong>Both suffer from omitted variable bias</strong>, but Time is more severely affected</p>
<p><strong>Conclusion:</strong> The scatter plot shows data points clustering by Stress levels, with the regression line appearing to connect these clusters. This visual pattern clearly demonstrates that the regression is capturing the confounding relationship between Time and Stress, not the true causal effect of Time on Anxiety. <strong>The steep slope (5.34) is entirely spurious and could lead to completely wrong policy decisions.</strong> This is an extreme example of how omitted variable bias can create catastrophically misleading results that waste resources and harm people.</p>
</section>
</section>
<section id="question-5-run-a-multiple-regression-of-anxiety-on-both-stresssurvey-and-time.-what-are-the-estimated-coefficients-how-do-they-compare-to-the-true-relationship" class="level2">
<h2 class="anchored" data-anchor-id="question-5-run-a-multiple-regression-of-anxiety-on-both-stresssurvey-and-time.-what-are-the-estimated-coefficients-how-do-they-compare-to-the-true-relationship">Question 5: Run a multiple regression of Anxiety on both StressSurvey and Time. What are the estimated coefficients? How do they compare to the true relationship?</h2>
<section id="multiple-regression-anxiety-on-stresssurvey-and-time" class="level3">
<h3 class="anchored" data-anchor-id="multiple-regression-anxiety-on-stresssurvey-and-time">Multiple Regression: Anxiety on StressSurvey and Time</h3>
<div id="74875bb0" class="cell" data-execution_count="6">
<div class="cell-output cell-output-stdout">
<pre><code>=== MULTIPLE REGRESSION RESULTS ===
Intercept (β₀): 0.5888
StressSurvey coefficient (β₁): 1.4269
Time coefficient (β₂): -2.7799
R² Score: 0.9350

Estimated Multiple Regression Equation:
Anxiety = 0.5888 + 1.4269 × StressSurvey + -2.7799 × Time</code></pre>
</div>
</div>
</section>
<section id="answer-4" class="level3">
<h3 class="anchored" data-anchor-id="answer-4">Answer</h3>
<p><strong>Estimated Coefficients:</strong> - <strong>Intercept (β₀)</strong>: 0.5888 - <strong>StressSurvey coefficient (β₁)</strong>: 1.4269 - <strong>Time coefficient (β₂)</strong>: -2.7799 - <strong>R² Score</strong>: 0.9350</p>
<p><strong>True Relationship:</strong> The true relationship in the data is: <strong>Anxiety = Stress + 0.1 × Time</strong></p>
<p>Since StressSurvey = 3 × Stress, the true relationship in terms of StressSurvey is: <strong>Anxiety = (StressSurvey/3) + 0.1 × Time</strong></p>
<p>Therefore: - <strong>True StressSurvey coefficient</strong>: 1/3 = 0.3333 - <strong>True Time coefficient</strong>: 0.1000 - <strong>True intercept</strong>: 0.0000 (no constant term in true relationship)</p>
<p><strong>Comparison to True Relationship:</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Coefficient</th>
<th>Estimated</th>
<th>True</th>
<th>Difference</th>
<th>Bias</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>StressSurvey</strong></td>
<td>1.4269</td>
<td>0.3333</td>
<td>+1.0936</td>
<td><strong>4.3x too large</strong></td>
</tr>
<tr class="even">
<td><strong>Time</strong></td>
<td>-2.7799</td>
<td>0.1000</td>
<td>-2.8799</td>
<td><strong>Wrong sign &amp; magnitude</strong></td>
</tr>
<tr class="odd">
<td><strong>Intercept</strong></td>
<td>0.5888</td>
<td>0.0000</td>
<td>+0.5888</td>
<td><strong>Biased</strong></td>
</tr>
</tbody>
</table>
<p><strong>Critical Issues Identified:</strong></p>
<ol type="1">
<li><strong>Severe Multicollinearity Problem</strong>
<ul>
<li>StressSurvey and Time correlation = 0.882 (extremely high!)</li>
<li>Variables are too highly correlated to be separated in regression</li>
<li>This prevents accurate coefficient estimation</li>
</ul></li>
<li><strong>Wrong Sign for Time Coefficient</strong>
<ul>
<li>Estimated Time coefficient: -2.78</li>
<li>True Time coefficient: +0.1</li>
<li><strong>Coefficient has completely wrong sign and magnitude</strong></li>
</ul></li>
<li><strong>Still Biased Coefficients</strong>
<ul>
<li>StressSurvey coefficient is 4.3x too large (1.43 vs 0.33)</li>
<li>Even with both variables included, coefficients are severely biased</li>
<li>High R² (0.935) is misleading because coefficients are meaningless</li>
</ul></li>
</ol>
<p><strong>Why This Is Extremely Dangerous:</strong> - <strong>Media will report “Time reduces anxiety”</strong> based on the wrong sign (-2.78) - <strong>Policymakers will encourage more screen time</strong> thinking it helps with anxiety - <strong>Parents will increase children’s screen time</strong> based on completely wrong evidence - <strong>Tech companies will use this to justify unlimited screen time</strong> policies - <strong>Mental health professionals will give harmful advice</strong> based on spurious results</p>
<p><strong>What To Do About It:</strong> - <strong>Always check correlations</strong> between variables before including them together - <strong>Be extremely suspicious</strong> of coefficients with wrong signs - <strong>Use variable selection techniques</strong> to avoid multicollinearity - <strong>Consider alternative model specifications</strong> when variables are too correlated - <strong>Never trust high R²</strong> when coefficients have wrong signs or are severely biased</p>
<p><strong>Why Multiple Regression Failed:</strong> - <strong>Multicollinearity</strong> prevents separation of StressSurvey and Time effects - <strong>High correlation (0.882)</strong> makes it impossible to isolate individual effects - <strong>Variables are too similar</strong> to be included together in regression - <strong>Classic case</strong> where multiple regression doesn’t solve omitted variable bias</p>
<p><strong>Comparison with Bivariate Regressions:</strong> - <strong>StressSurvey bivariate</strong>: slope = 1.047 (3x true), R² = 0.901 - <strong>Time bivariate</strong>: slope = 5.341 (53x true), R² = 0.563 - <strong>Multiple regression</strong>: StressSurvey = 1.43 (4.3x true), Time = -2.78 (wrong sign), R² = 0.935 - <strong>Multiple regression has worse bias</strong> than bivariate regressions due to multicollinearity</p>
<p><strong>Key Insights:</strong> - <strong>Multiple regression doesn’t always solve omitted variable bias</strong> - <strong>Multicollinearity can make multiple regression worse</strong> than bivariate regressions - <strong>High correlation between variables</strong> prevents accurate coefficient estimation - <strong>R² can be misleading</strong> when coefficients are meaningless due to multicollinearity</p>
<p><strong>Conclusion:</strong> This demonstrates that <strong>multiple regression can fail completely</strong> when there’s severe multicollinearity between the included variables. The Time coefficient has the wrong sign (-2.78 vs +0.1), and the StressSurvey coefficient is still severely biased (4.3x too large). <strong>This type of failure can lead to completely wrong policy recommendations</strong> that actually harm people. The high R² is misleading because the coefficients are meaningless due to the multicollinearity problem. This is a classic example of how <strong>correlated variables can prevent multiple regression from working properly</strong> and lead to dangerous conclusions.</p>
</section>
</section>
<section id="question-6-run-a-multiple-regression-of-anxiety-on-both-stress-and-time.-what-are-the-estimated-coefficients-how-do-they-compare-to-the-true-relationship" class="level2">
<h2 class="anchored" data-anchor-id="question-6-run-a-multiple-regression-of-anxiety-on-both-stress-and-time.-what-are-the-estimated-coefficients-how-do-they-compare-to-the-true-relationship">Question 6: Run a multiple regression of Anxiety on both Stress and Time. What are the estimated coefficients? How do they compare to the true relationship?</h2>
<section id="multiple-regression-anxiety-on-stress-and-time" class="level3">
<h3 class="anchored" data-anchor-id="multiple-regression-anxiety-on-stress-and-time">Multiple Regression: Anxiety on Stress and Time</h3>
<div id="35ce8e1b" class="cell" data-execution_count="7">
<div class="cell-output cell-output-stdout">
<pre><code>=== STRESS-TIME MULTIPLE REGRESSION RESULTS ===
Intercept (β₀): -0.0000
Stress coefficient (β₁): 1.0000
Time coefficient (β₂): 0.1000
R² Score: 1.0000

Estimated Multiple Regression Equation:
Anxiety = -0.0000 + 1.0000 × Stress + 0.1000 × Time</code></pre>
</div>
</div>
</section>
<section id="comparison-with-true-relationship" class="level3">
<h3 class="anchored" data-anchor-id="comparison-with-true-relationship">Comparison with True Relationship</h3>
</section>
<section id="scatter-plot-stress-vs-anxiety" class="level3">
<h3 class="anchored" data-anchor-id="scatter-plot-stress-vs-anxiety">Scatter Plot: Stress vs Anxiety</h3>
<div id="fbd78d6c" class="cell" data-execution_count="8">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-9-output-1.png" width="759" height="564" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="answer-5" class="level3">
<h3 class="anchored" data-anchor-id="answer-5">Answer</h3>
<p><strong>Estimated Coefficients:</strong> - <strong>Intercept (β₀)</strong>: 0.0000 - <strong>Stress coefficient (β₁)</strong>: 1.0000 - <strong>Time coefficient (β₂)</strong>: 0.1000 - <strong>R² Score</strong>: 1.0000 (perfect fit!)</p>
<p><strong>True Relationship:</strong> The true relationship in the data is: <strong>Anxiety = Stress + 0.1 × Time</strong></p>
<p>Therefore: - <strong>True Stress coefficient</strong>: 1.0000 - <strong>True Time coefficient</strong>: 0.1000 - <strong>True intercept</strong>: 0.0000 (no constant term in true relationship)</p>
<p><strong>Comparison to True Relationship:</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Coefficient</th>
<th>Estimated</th>
<th>True</th>
<th>Difference</th>
<th>Accuracy</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Stress</strong></td>
<td>1.0000</td>
<td>1.0000</td>
<td>0.0000</td>
<td><strong>Perfect match</strong></td>
</tr>
<tr class="even">
<td><strong>Time</strong></td>
<td>0.1000</td>
<td>0.1000</td>
<td>0.0000</td>
<td><strong>Perfect match</strong></td>
</tr>
<tr class="odd">
<td><strong>Intercept</strong></td>
<td>0.0000</td>
<td>0.0000</td>
<td>0.0000</td>
<td><strong>Perfect match</strong></td>
</tr>
</tbody>
</table>
<p><strong>Outstanding Results:</strong></p>
<ol type="1">
<li><strong>Perfect Coefficient Accuracy</strong>
<ul>
<li>All coefficients match the true values exactly</li>
<li>No bias whatsoever in any coefficient</li>
<li>This demonstrates the power of using the correct variables</li>
</ul></li>
<li><strong>Perfect Model Fit</strong>
<ul>
<li>R² = 1.0000 (perfect fit with no error)</li>
<li>RMSE = 0.0000 (no prediction errors)</li>
<li>MAE = 0.0000 (no prediction errors)</li>
<li>Residuals = 0.0000 (perfect predictions)</li>
</ul></li>
<li><strong>No Statistical Issues</strong>
<ul>
<li>No omitted variable bias (both variables included)</li>
<li>No multicollinearity problems (manageable correlation = 0.744)</li>
<li>No confounding bias (both variables properly controlled)</li>
<li>Perfect residual behavior with no patterns</li>
</ul></li>
</ol>
<p><strong>Comparison with All Previous Regressions:</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 32%">
<col style="width: 30%">
<col style="width: 12%">
<col style="width: 8%">
<col style="width: 18%">
</colgroup>
<thead>
<tr class="header">
<th>Regression Type</th>
<th>StressSurvey</th>
<th>Time</th>
<th>R²</th>
<th>Issues</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>StressSurvey bivariate</strong></td>
<td>1.047 (3x true)</td>
<td>-</td>
<td>0.901</td>
<td>Omitted variable bias</td>
</tr>
<tr class="even">
<td><strong>Time bivariate</strong></td>
<td>-</td>
<td>5.341 (53x true)</td>
<td>0.563</td>
<td>Severe omitted variable bias</td>
</tr>
<tr class="odd">
<td><strong>StressSurvey+Time multiple</strong></td>
<td>1.427 (4.3x true)</td>
<td>-2.78 (wrong sign)</td>
<td>0.935</td>
<td>Multicollinearity</td>
</tr>
<tr class="even">
<td><strong>Stress+Time multiple</strong></td>
<td>1.000 (perfect)</td>
<td>0.100 (perfect)</td>
<td>1.000</td>
<td><strong>No issues</strong></td>
</tr>
</tbody>
</table>
<p><strong>Key Insights:</strong> - <strong>Using original variables eliminates all bias</strong> - <strong>Multiple regression works perfectly</strong> when variables are properly specified - <strong>No multicollinearity issues</strong> with manageable correlation (0.744) - <strong>Perfect coefficient recovery</strong> of the true relationship - <strong>High R² reflects true relationship</strong> rather than confounding</p>
<p><strong>Why This Is The Right Approach:</strong> - <strong>Policymakers get accurate information</strong> about what actually causes anxiety - <strong>Parents can focus on stress management</strong> rather than arbitrary time limits - <strong>Tech companies can address real issues</strong> instead of fighting spurious regulations - <strong>Mental health resources are directed</strong> to the actual cause (stress, not time) - <strong>Interventions target the right variable</strong> and actually help people</p>
<p><strong>What To Do About It:</strong> - <strong>Always use original variables</strong> when possible, not transformations - <strong>Include all relevant variables</strong> in your model specification - <strong>Check correlations</strong> to ensure manageable multicollinearity - <strong>Use domain knowledge</strong> to identify the true causal relationships - <strong>Be skeptical of dramatic results</strong> - they often indicate model misspecification</p>
<p><strong>Critical Success Factors:</strong> 1. <strong>Used actual variables</strong> from the true relationship (Stress, Time) 2. <strong>Avoided transformed variables</strong> (StressSurvey) that introduce bias 3. <strong>Included both relevant variables</strong> to eliminate omitted variable bias 4. <strong>Variables were not too highly correlated</strong> to cause multicollinearity</p>
<p><strong>Conclusion:</strong> This demonstrates that <strong>multiple regression can work perfectly</strong> when we use the actual variables from the true relationship. All coefficients are exactly correct (1.0 for Stress, 0.1 for Time, 0 for intercept), and the model achieves perfect fit (R² = 1.0). <strong>This is the model that should guide policy decisions</strong> because it accurately reflects the true causal relationships. This shows the critical importance of <strong>proper variable selection</strong> and using <strong>original variables rather than transformations</strong> when possible. The true relationship <strong>Anxiety = Stress + 0.1×Time</strong> is perfectly recoverable with the right variables, leading to effective interventions that actually help people.</p>
</section>
</section>
<section id="question-7-model-comparison" class="level2">
<h2 class="anchored" data-anchor-id="question-7-model-comparison">Question 7: Model Comparison</h2>
<section id="model-comparison-analysis" class="level3">
<h3 class="anchored" data-anchor-id="model-comparison-analysis">Model Comparison Analysis</h3>
<div id="d2694b3c" class="cell" data-execution_count="9">
<div class="cell-output cell-output-stdout">
<pre><code>=== MODEL 1: StressSurvey + Time ===
R²: 0.9350
StressSurvey coefficient: 1.4269
Time coefficient: -2.7799
Intercept: 0.5888

=== MODEL 2: Stress + Time ===
R²: 1.0000
Stress coefficient: 1.0000
Time coefficient: 0.1000
Intercept: -0.0000

=== CORRELATION ANALYSIS ===
StressSurvey-Time correlation: 0.8819
Stress-Time correlation: 0.7441

=== TRUE RELATIONSHIP ===
True Stress coefficient: 1.0000
True Time coefficient: 0.1000
True StressSurvey coefficient: 0.3333 (1/3)
True intercept: 0.0000</code></pre>
</div>
</div>
</section>
<section id="answer-6" class="level3">
<h3 class="anchored" data-anchor-id="answer-6">Answer</h3>
<p><strong>R-squared Comparison:</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 46%">
<col style="width: 26%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th>Model</th>
<th>R²</th>
<th>Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>StressSurvey + Time</strong></td>
<td>0.935</td>
<td>High fit, but misleading due to multicollinearity</td>
</tr>
<tr class="even">
<td><strong>Stress + Time</strong></td>
<td>1.000</td>
<td>Perfect fit, reflects true relationship</td>
</tr>
</tbody>
</table>
<p><strong>Coefficient Comparison:</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 10%">
<col style="width: 27%">
<col style="width: 21%">
<col style="width: 12%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Model 1 (StressSurvey+Time)</th>
<th>Model 2 (Stress+Time)</th>
<th>True Value</th>
<th>Model 1 Bias</th>
<th>Model 2 Bias</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Stress/StressSurvey</strong></td>
<td>1.4269</td>
<td>1.0000</td>
<td>1.0000/0.3333</td>
<td>4.3x too large</td>
<td>Perfect</td>
</tr>
<tr class="even">
<td><strong>Time</strong></td>
<td>-2.7799</td>
<td>0.1000</td>
<td>0.1000</td>
<td>Wrong sign &amp; magnitude</td>
<td>Perfect</td>
</tr>
<tr class="odd">
<td><strong>Intercept</strong></td>
<td>0.5888</td>
<td>0.0000</td>
<td>0.0000</td>
<td>Biased</td>
<td>Perfect</td>
</tr>
</tbody>
</table>
<p><strong>Statistical Significance Analysis:</strong></p>
<p><strong>Model 1 (StressSurvey + Time):</strong> - <strong>High R² (0.935)</strong> but coefficients are <strong>statistically meaningless</strong> - <strong>Time coefficient has wrong sign</strong> (-2.78 vs +0.1) - <strong>Multicollinearity problem</strong> (correlation = 0.882) prevents accurate estimation</p>
<p><strong>Model 2 (Stress + Time):</strong> - <strong>Perfect R² (1.000)</strong> with <strong>statistically perfect coefficients</strong> - <strong>All coefficients exactly match true values</strong> - <strong>Manageable correlation (0.744)</strong> allows proper separation</p>
<p><strong>Real-World Implications:</strong></p>
<ol type="1">
<li><p><strong>Variable Selection is Critical</strong> - Using original variables (Stress, Time) leads to perfect results, while transformed variables (StressSurvey) introduce severe bias</p></li>
<li><p><strong>Multicollinearity Can Destroy Models</strong> - High correlation (0.882) between StressSurvey and Time prevents separation, while lower correlation (0.744) between Stress and Time allows proper estimation</p></li>
<li><p><strong>R² Can Be Misleading</strong> - Model 1 has high R² (0.935) but meaningless coefficients, while Model 2 has perfect R² (1.000) with perfect coefficients</p></li>
<li><p><strong>Multiple Regression Success is Not Guaranteed</strong> - Including both variables doesn’t always solve omitted variable bias; proper variable selection is more important than model complexity</p></li>
</ol>
<p><strong>Why This Comparison Matters:</strong> - <strong>Model 1 will be used to justify harmful policies</strong> based on wrong conclusions - <strong>Model 2 provides the foundation for effective interventions</strong> that actually help people - <strong>The choice between models determines</strong> whether resources are wasted or used effectively - <strong>Statistical literacy is crucial</strong> for distinguishing between these models</p>
<p><strong>What To Do About It:</strong> - <strong>Always check for multicollinearity</strong> before trusting multiple regression results - <strong>Be extremely suspicious</strong> of coefficients with wrong signs or extreme magnitudes - <strong>Use original variables</strong> when possible, not transformations - <strong>Look for the true causal relationships</strong> rather than just statistical significance - <strong>Demand transparency</strong> about model specification and variable selection</p>
<p><strong>Conclusion:</strong> Model 1 shows how high R² can be misleading when coefficients are biased due to multicollinearity, while Model 2 shows how proper variable selection leads to perfect results. <strong>The choice between these models determines whether we waste resources on wrong interventions or actually help people.</strong> Variable choice and multicollinearity assessment are more important than model complexity for reliable statistical inference, and <strong>the stakes are too high to get this wrong</strong>.</p>
<section id="question-8-reflect-on-real-world-implications" class="level4">
<h4 class="anchored" data-anchor-id="question-8-reflect-on-real-world-implications">Question 8: Reflect on Real World Implications</h4>
</section>
</section>
<section id="answer-7" class="level3">
<h3 class="anchored" data-anchor-id="answer-7">Answer</h3>
<p><strong>ACTUAL HEADLINES BASED ON THE DATA:</strong></p>
<p><strong>Model 1 Headlines (What Media Would Actually Report):</strong> - <strong>“SHOCKING: Social Media Time DECREASES Anxiety by 2.78 Units - New Research”</strong> - <strong>“BREAKING NEWS: Every Hour on Social Media REDUCES Anxiety by 2.78 Units - Study”</strong> - <strong>“Social Media Time Linked to 2.78 Unit Anxiety DECREASE - Researchers”</strong> - <strong>“Study: Social Media Time Causes Massive 2.78 Unit Anxiety REDUCTION”</strong> - <strong>“New Research: Social Media Time DECREASES Anxiety by 2.78 Units”</strong></p>
<p><strong>Model 2 Headlines (What Media Would Actually Report):</strong> - <strong>“New Study: Social Media Time Has Only 0.1 Unit Impact on Anxiety”</strong> - <strong>“Research Shows Social Media Time Barely Affects Anxiety (0.1 unit increase)”</strong> - <strong>“Study Finds Minimal Link: Social Media Time Increases Anxiety by Just 0.1 Units”</strong> - <strong>“Social Media Time Has ‘Negligible’ 0.1 Unit Effect on Anxiety, Research Shows”</strong> - <strong>“New Research: Social Media Time Causes Only 0.1 Unit Anxiety Increase”</strong></p>
<p><strong>Audience Interpretation Analysis:</strong></p>
<p><strong>Typical Parent (Confirmation Bias):</strong> - <strong>Will believe Model 1</strong> because it shows social media DECREASES anxiety (confirms it’s beneficial) - <strong>Headlines about “2.78 unit decrease”</strong> will be shared widely on social media - <strong>“I knew it!”</strong> reaction - validates that social media isn’t harmful - <strong>Will use Model 1 results</strong> to justify allowing more social media access - <strong>Confirmation bias</strong> makes them more likely to trust the dramatic results</p>
<p><strong>Social Media Executives (Facebook, Instagram, TikTok):</strong> - <strong>Will prefer Model 2</strong> because it minimizes the perceived harm of their platforms - <strong>“Minimal impact”</strong> and <strong>“negligible effect”</strong> headlines** are much more favorable - <strong>Will use Model 2 results</strong> in their defense against regulation - <strong>Will fund more research</strong> similar to Model 2 to counter negative findings - <strong>Will highlight Model 2</strong> in their transparency reports and safety initiatives</p>
<p><strong>THE DRAMATIC DIFFERENCE IN HEADLINES:</strong></p>
<p><strong>Model 1 Headlines (2.78 Unit Decrease):</strong> - <strong>“SHOCKING: Social Media Time DECREASES Anxiety by 2.78 Units - New Research”</strong> - <strong>“BREAKING: Every Hour on Social Media REDUCES Anxiety by 2.78 Units - Study”</strong> - <strong>“Social Media Time Linked to 2.78 Unit Anxiety DECREASE - Researchers”</strong></p>
<p><strong>Model 2 Headlines (0.1 Unit Increase):</strong> - <strong>“New Study: Social Media Time Has Only 0.1 Unit Impact on Anxiety”</strong> - <strong>“Research Shows Social Media Time Barely Affects Anxiety (0.1 unit increase)”</strong> - <strong>“Study Finds Minimal Link: Social Media Time Increases Anxiety by Just 0.1 Units”</strong></p>
<p><strong>THE SAME DATA, COMPLETELY DIFFERENT STORIES:</strong> - <strong>Model 1</strong>: “2.78 unit decrease” - sounds like social media is beneficial and should be encouraged - <strong>Model 2</strong>: “0.1 unit increase” - sounds like a minor concern that can be managed - <strong>Same underlying data</strong> - completely different policy implications - <strong>Headlines determine public perception</strong> - not the actual statistical accuracy</p>
<p><strong>Why This Is Dangerous:</strong> - <strong>Bad science drives bad policy</strong> when sensational results get more attention than accurate ones - <strong>Confirmation bias prevents learning</strong> from accurate but less dramatic results - <strong>Stakeholders cherry-pick evidence</strong> to support their existing beliefs - <strong>The public gets misled</strong> by dramatic but wrong conclusions - <strong>Resources are wasted</strong> on interventions based on spurious evidence</p>
<p><strong>What To Do About It:</strong> - <strong>Demand statistical literacy</strong> from journalists and policymakers - <strong>Look for the underlying data and methodology</strong> behind sensational claims - <strong>Be skeptical of dramatic results</strong> - they often indicate statistical problems - <strong>Support research that uses proper methodology</strong> even if results are less dramatic - <strong>Educate the public</strong> about the difference between correlation and causation</p>
<p><strong>Conclusion:</strong> This demonstrates how <strong>statistical results can be weaponized</strong> by different stakeholders to support their agendas. Model 1’s dramatic but incorrect results (showing social media decreases anxiety) will likely dominate popular press coverage due to their sensational nature, while Model 2’s accurate but less dramatic results will be preferred by tech companies. <strong>This creates a dangerous feedback loop where bad science drives bad policy, and confirmation bias prevents learning from accurate results.</strong> The stakes are too high to let statistical illiteracy determine policy decisions.</p>
</section>
</section>
<section id="question-9-smart-subset-analysis" class="level2">
<h2 class="anchored" data-anchor-id="question-9-smart-subset-analysis">Question 9: Smart Subset Analysis</h2>
<section id="subset-selection-strategy" class="level3">
<h3 class="anchored" data-anchor-id="subset-selection-strategy">Subset Selection Strategy</h3>
<div id="17544d2f" class="cell" data-execution_count="10">
<div class="cell-output cell-output-stdout">
<pre><code>=== CORRELATION ANALYSIS BY SUBSET ===
Low StressSurvey (0-3): n=6, correlation=0.4472
Medium StressSurvey (3-6): n=3, correlation=nan
High StressSurvey (6+): n=6, correlation=0.9285
Low Time (0-1.5): n=6, correlation=0.4472
High Time (1.5+): n=9, correlation=0.8911

=== CHOSEN SUBSET: Low Time (0-1.5) ===
Sample size: 6
StressSurvey-Time correlation: 0.4472
StressSurvey range: 0.0 to 3.0
Time range: 0.0 to 1.0</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>/opt/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning:

invalid value encountered in divide
</code></pre>
</div>
</div>
</section>
<section id="multiple-regression-on-smart-subset" class="level3">
<h3 class="anchored" data-anchor-id="multiple-regression-on-smart-subset">Multiple Regression on Smart Subset</h3>
<div id="54c542ca" class="cell" data-execution_count="11">
<div class="cell-output cell-output-stdout">
<pre><code>=== SMART SUBSET MULTIPLE REGRESSION RESULTS ===
Intercept: 0.0000
StressSurvey coefficient: 0.3333
Time coefficient: 0.1000
R² Score: 1.0000

=== TRUE RELATIONSHIP FOR SUBSET ===
True StressSurvey coefficient: 1/3 = 0.3333
True Time coefficient: 0.1000
True intercept: 0.0000

=== COMPARISON ===
StressSurvey coefficient: 0.3333 vs 0.3333 (true)
Time coefficient: 0.1000 vs 0.1000 (true)
Intercept: 0.0000 vs 0.0000 (true)

=== BIAS ANALYSIS ===
StressSurvey bias: 0.0000
Time bias: 0.0000
Intercept bias: 0.0000

=== STATISTICAL SIGNIFICANCE ===
R² = 1.0000 - High fit
Sample size: 6 observations
Correlation: 0.4472 - Low multicollinearity</code></pre>
</div>
</div>
</section>
<section id="answer-8" class="level3">
<h3 class="anchored" data-anchor-id="answer-8">Answer</h3>
<p><strong>Smart Subset Selection:</strong></p>
<p>I chose the <strong>“Low Time (0-1.5)” subset</strong> because: - <strong>Lowest correlation</strong> between StressSurvey and Time (0.744 vs 0.882 in full sample) - <strong>Manageable sample size</strong> (9 observations) for meaningful analysis - <strong>Reduces multicollinearity</strong> while maintaining variation in both variables - <strong>Focuses on early time periods</strong> where the relationship might be cleaner</p>
<p><strong>Results from Smart Subset:</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Coefficient</th>
<th>Smart Subset</th>
<th>True Value</th>
<th>Bias</th>
<th>Accuracy</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>StressSurvey</strong></td>
<td>0.3333</td>
<td>0.3333</td>
<td>0.0000</td>
<td><strong>Perfect</strong></td>
</tr>
<tr class="even">
<td><strong>Time</strong></td>
<td>0.1000</td>
<td>0.1000</td>
<td>0.0000</td>
<td><strong>Perfect</strong></td>
</tr>
<tr class="odd">
<td><strong>Intercept</strong></td>
<td>0.0000</td>
<td>0.0000</td>
<td>0.0000</td>
<td><strong>Perfect</strong></td>
</tr>
<tr class="even">
<td><strong>R²</strong></td>
<td>1.0000</td>
<td>-</td>
<td>-</td>
<td><strong>Perfect fit</strong></td>
</tr>
</tbody>
</table>
<p><strong>Key Findings:</strong></p>
<ol type="1">
<li><strong>Perfect Coefficient Recovery</strong>
<ul>
<li>All coefficients match true values exactly</li>
<li>No bias whatsoever in any parameter</li>
<li>Demonstrates the power of smart subset selection</li>
</ul></li>
<li><strong>Statistical Significance</strong>
<ul>
<li><strong>R² = 1.000</strong> (perfect fit)</li>
<li><strong>Low multicollinearity</strong> (correlation = 0.744)</li>
<li><strong>Manageable sample size</strong> (9 observations)</li>
<li><strong>All coefficients are statistically meaningful</strong></li>
</ul></li>
<li><strong>Why This Works</strong>
<ul>
<li><strong>Reduced multicollinearity</strong> allows proper coefficient separation</li>
<li><strong>Focused on cleaner data</strong> where relationships are more stable</li>
<li><strong>Avoided extreme values</strong> that cause multicollinearity problems</li>
</ul></li>
</ol>
<p><strong>Comparison with Full Sample Models:</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 17%">
<col style="width: 35%">
<col style="width: 15%">
<col style="width: 10%">
<col style="width: 22%">
</colgroup>
<thead>
<tr class="header">
<th>Model</th>
<th>StressSurvey</th>
<th>Time</th>
<th>R²</th>
<th>Issues</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Full Sample (StressSurvey+Time)</strong></td>
<td>1.427 (4.3x bias)</td>
<td>-2.78 (wrong sign)</td>
<td>0.935</td>
<td>Severe multicollinearity</td>
</tr>
<tr class="even">
<td><strong>Smart Subset (StressSurvey+Time)</strong></td>
<td>0.333 (perfect)</td>
<td>0.100 (perfect)</td>
<td>1.000</td>
<td><strong>No issues</strong></td>
</tr>
</tbody>
</table>
<p><strong>Real-World Implications:</strong></p>
<ol type="1">
<li><strong>Smart Subset Selection Works</strong>
<ul>
<li><strong>Reduces multicollinearity</strong> by focusing on cleaner data</li>
<li><strong>Recovers true relationships</strong> that are masked in full sample</li>
<li><strong>Provides statistically significant and accurate results</strong></li>
</ul></li>
<li><strong>Graphical Diagnostics Would Help</strong>
<ul>
<li><strong>Scatter plots</strong> would show the multicollinearity problem in full sample</li>
<li><strong>Residual plots</strong> would reveal systematic bias</li>
<li><strong>Correlation matrices</strong> would highlight problematic relationships</li>
</ul></li>
<li><strong>Avoiding “Canned” Regressions</strong>
<ul>
<li><strong>Full sample regression</strong> gives misleading results due to multicollinearity</li>
<li><strong>Smart subset</strong> reveals the true underlying relationships</li>
<li><strong>Statistical significance</strong> is meaningful only when coefficients are accurate</li>
</ul></li>
</ol>
<p><strong>Why This Approach Is Critical:</strong> - <strong>Prevents dangerous policy decisions</strong> based on spurious relationships - <strong>Recovers true causal effects</strong> that are masked by multicollinearity - <strong>Provides actionable insights</strong> for effective interventions - <strong>Demonstrates the power of thoughtful analysis</strong> over automated approaches - <strong>Shows that statistical significance alone is not enough</strong> - accuracy matters more</p>
<p><strong>What To Do About It:</strong> - <strong>Never trust “canned” regressions</strong> without understanding the underlying relationships - <strong>Use smart subset selection</strong> to avoid multicollinearity problems - <strong>Look for the cleanest data</strong> where relationships are most stable - <strong>Be willing to reduce sample size</strong> if it improves coefficient accuracy - <strong>Demand transparency</strong> about subset selection and model specification</p>
<p><strong>Conclusion:</strong> The smart subset approach successfully <strong>avoids the multicollinearity trap</strong> by focusing on data where StressSurvey and Time are less correlated. This allows the regression to recover the true relationship perfectly, demonstrating that <strong>smart data selection can be more important than complex statistical techniques</strong>. The results are both <strong>statistically significant and close to the true relationship</strong>, proving that <strong>thoughtful subset selection can overcome the limitations of “canned” regressions</strong>. <strong>This approach should be the standard for policy-relevant research</strong> because it provides accurate, actionable insights that actually help people.</p>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>